### ISSUE TITLE
Does it work on Windows?

### ISSUE THREAD

**Issue by avh4** [avh4/elm-upgrade#1]
I haven't tried it on Windows yet.  It might work, or it might not.

If you try it on Windows, please let me know what happens.

 - [x] Does the `which` package work?
 - [x] Do the executables get invoked properly?
 - [x] Does the elm-package.json get saved correctly?

**Comment by manuscrypt** [comment]
Hi,

In my case, it doesn't work out of the box, because I installed elm using the platform-installer and not npm. if you want me to try, I can uninstall the binaries and try it with npm-installed elm.

Cheers
Manuel

============================================

λ **cd elm-pixelfont\**

λ **npm install -g elm-upgrade**
C:\Users\manuel.baumann\AppData\Roaming\npm\elm-upgrade -> C:\Users\manuel.baumann\AppData\Roaming\npm\node_modules\elm-upgrade\upgrade.js
C:\Users\manuel.baumann\AppData\Roaming\npm
`-- elm-upgrade@0.18.0-alpha
  +-- fs-extra@0.30.0
  | +-- graceful-fs@4.1.10
  | +-- jsonfile@2.4.0
  | +-- klaw@1.3.1
  | +-- path-is-absolute@1.0.1
  | `-- rimraf@2.5.4
  |   `-- glob@7.1.1
  |     +-- fs.realpath@1.0.0
  |     +-- inflight@1.0.6
  |     +-- inherits@2.0.3
  |     `-- minimatch@3.0.3
  |       `-- brace-expansion@1.1.6
  |         +-- balanced-match@0.4.2
  |         `-- concat-map@0.0.1
  +-- simple-get@2.3.0
  | +-- once@1.4.0
  | | `-- wrappy@1.0.2
  | +-- simple-concat@1.0.0
  | `-- unzip-response@2.0.1
  `-- which@1.2.12
    `-- isexe@1.1.2

λ **elm-upgrade**
INFO: Found elm at C:\Program Files (x86)\Elm Platform\0.17.1\bin\elm.EXE
INFO: Found elm-format at C:\Program Files (x86)\Elm Platform\0.17.1\bin\elm-format.EXE
ERROR: Elm 0.18 required, but found Elm Platform 0.17.1
Install Elm here https://guide.elm-lang.org/get_started.html#install

λ **npm install -g elm@0.18.0-beta**
C:\Users\manuel.baumann\AppData\Roaming\npm\elm -> C:\Users\manuel.baumann\AppData\Roaming\npm\node_modules\elm\binwrappers\elm
C:\Users\manuel.baumann\AppData\Roaming\npm\elm-make -> C:\Users\manuel.baumann\AppData\Roaming\npm\node_modules\elm\binwrappers\elm-make
C:\Users\manuel.baumann\AppData\Roaming\npm\elm-package -> C:\Users\manuel.baumann\AppData\Roaming\npm\node_modules\elm\binwrappers\elm-package
C:\Users\manuel.baumann\AppData\Roaming\npm\elm-reactor -> C:\Users\manuel.baumann\AppData\Roaming\npm\node_modules\elm\binwrappers\elm-reactor
C:\Users\manuel.baumann\AppData\Roaming\npm\elm-repl -> C:\Users\manuel.baumann\AppData\Roaming\npm\node_modules\elm\binwrappers\elm-repl

> elm@0.18.0-beta install C:\Users\manuel.baumann\AppData\Roaming\npm\node_modules\elm
> node install.js

Downloading Elm binaries from https://dl.bintray.com/elmlang/elm-platform/0.18.0/win32-x64.tar.gz
C:\Users\manuel.baumann\AppData\Roaming\npm
`-- elm@0.18.0-beta
  +-- mkdirp@0.5.1
(.. a bunch of packages)

λ elm-upgrade
INFO: Found elm at C:\Program Files (x86)\Elm Platform\0.17.1\bin\elm.EXE
INFO: Found elm-format at C:\Program Files (x86)\Elm Platform\0.17.1\bin\elm-format.EXE
ERROR: Elm 0.18 required, but found Elm Platform 0.17.1
Install Elm here https://guide.elm-lang.org/get_started.html#install

**Comment by manuscrypt** [comment]
Follow up:

Uninstalled elm-plattform brinaries, installed elm 0.18 beta via npm.

λ elm-format
elm-format-0.17 0.4.0-alpha

λ elm-upgrade
INFO: Found elm at C:\Users\manuel.baumann\AppData\Roaming\npm\elm.CMD
INFO: Found elm-format at C:\Users\manuel.baumann\AppData\Roaming\elm\elm-format.EXE
INFO: Found Elm Platform 0.18.0
ERROR: elm-format >= 0.5.0-alpha required, but found elm-format-0.17 0.4.0-alpha
You can download Elm format here https://github.com/avh4/elm-format#installation-

where can i get elm-format 0.5.0-alpha?

**Comment by avh4** [comment]
The new elm-format is now published: https://github.com/avh4/elm-format#installation-

**Comment by manuscrypt** [comment]
I installed latest elm-format and upgraded elm-upgrade. This is what I get on the same project:

C:\my\code\elm\elm-pixelfont (master)
λ where elm-upgrade
C:\Users\manuel.baumann\AppData\Roaming\npm\elm-upgrade
C:\Users\manuel.baumann\AppData\Roaming\npm\elm-upgrade.cmd

λ elm-upgrade
INFO: Found elm at C:\Users\manuel.baumann\AppData\Roaming\npm\elm.CMD
INFO: Found Elm Platform 0.18.0
INFO: Found elm-format at C:\Users\manuel.baumann\AppData\Roaming\elm\elm-format.EXE
INFO: Found 0.5.2-alpha
INFO: Cleaning ./elm-stuff before upgrading
INFO: Changing elm-package.json#elm-version to "0.18.0 <= v < 0.19.0"
INFO: Removing all dependencies from elm-package.json to reinstall them
INFO: Switching from elm-community/elm-linear-algebra (deprecated) to elm-community/linear-algebra
INFO: Installing latest version of elm-community/linear-algebra
Failed to upgrade elm-community/linear-algebra! Reverting changes..
INFO: Installing latest version of elm-community/list-extra
Failed to upgrade elm-community/list-extra! Reverting changes..
INFO: Installing latest version of elm-community/result-extra
Failed to upgrade elm-community/result-extra! Reverting changes..
INFO: Installing latest version of elm-lang/core
Failed to upgrade elm-lang/core! Reverting changes..
INFO: Installing latest version of elm-lang/html
Failed to upgrade elm-lang/html! Reverting changes..
INFO: Installing latest version of elm-lang/svg
Failed to upgrade elm-lang/svg! Reverting changes..
INFO: Installing latest version of eskimoblood/elm-color-extra
Failed to upgrade eskimoblood/elm-color-extra! Reverting changes..
INFO: Installing latest version of fredcy/elm-parseint
Failed to upgrade fredcy/elm-parseint! Reverting changes..
INFO: Upgrading *.elm files in src/
INFO: Upgrading *.elm files in examples/


SUCCESS! Your project's dependencies and code have been upgraded.
However, your project may not yet compile due to API changes in your
dependencies.

See https://github.com/elm-lang/elm-platform/blob/master/upgrade-docs/0.18.md
and the documentation for your dependencies for more information.

How can I get more verbose output (if) ? Anything else I can do?

**Comment by avh4** [comment]
Thanks!  it all looks good.

**Comment by manuscrypt** [comment]
**Failed to upgrade elm-community/linear-algebra! Reverting changes..**

**Comment by avh4** [comment]
oh... darn, okay, I know why this is failing.  Will fix tonight.

**Comment by avh4** [comment]
Just released 0.18.6, which hopefully fixes this issue finally.

**Comment by manuscrypt** [comment]
First of all, thank you for your hard work!

I just wanted to try 0.18.6, but I am not getting it through the official
npm repos yet.

**Comment by avh4** [comment]
I'm pretty sure I published it correctly, and I see it now on npmjs website.  Hopefully it will be there when to try again

**Comment by avh4** [comment]
0.18.7 is now published, and seems like people have had success on Windows now.
